/*
 * generated by Xtext 2.25.0
 */
package org.mk4h.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.mk4h.PuddleRuntimeModule;
import org.mk4h.PuddleStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PuddleIdeSetup extends PuddleStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PuddleRuntimeModule(), new PuddleIdeModule()));
	}
	
}
