/*
 * generated by Xtext 2.25.0
 */
package org.mk4h.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PuddleUiModule extends AbstractPuddleUiModule {

	public PuddleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
