/*
 * generated by Xtext 2.25.0
 */
package org.mk4h;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PuddleStandaloneSetup extends PuddleStandaloneSetupGenerated {

	public static void doSetup() {
		new PuddleStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
