/*
 * generated by Xtext 2.25.0
 */
package org.mk4h;

import org.eclipse.xtext.conversion.IValueConverterService;
import org.mk4h.conversion.PuddleValueConverterService;
/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PuddleRuntimeModule extends AbstractPuddleRuntimeModule {
	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
        return PuddleValueConverterService.class;
    }
}
